import { Router } from 'express';
import { getUser, kakaoLogin, kakaoSignUp, listUsers, me, testLogin, testSignUp, updateUser, updateUserRole } from '../controllers/authController.js';
import { allowRoles, authenticate } from '../middleware/auth.js';
const router = Router();
router.post('/kakao/signup', kakaoSignUp);
router.post('/kakao/login', kakaoLogin);
router.post('/test/signup', testSignUp);
router.post('/test/login', testLogin);
router.get('/me', authenticate, me);
router.get('/users', authenticate, allowRoles('master', 'admin'), listUsers);
router.get('/users/:id', authenticate, allowRoles('master', 'admin'), getUser);
router.patch('/users/:id', authenticate, allowRoles('master', 'admin'), updateUser);
router.patch('/users/:id/role', authenticate, allowRoles('master'), updateUserRole);
export default router;
