import { Router } from 'express';
import { customerMe, deleteCustomerAccount, deleteManagedCustomer, deleteMyAccount, deleteUser, getCustomer, getUser, kakaoCustomerLogin, kakaoCustomerSignUp, kakaoLogin, kakaoSignUp, listCustomers, listUsers, me, testLogin, testSignUp, updateCustomer, updateUser, updateUserRole } from '../controllers/authController.js';
import { allowRoles, authenticate } from '../middleware/auth.js';
import { authenticateCustomer } from '../middleware/customerAuth.js';
const router = Router();
router.post('/kakao/signup', kakaoSignUp);
router.post('/kakao/user/signup', kakaoCustomerSignUp);
router.post('/kakao/user/login', kakaoCustomerLogin);
router.post('/kakao/login', kakaoLogin);
router.post('/test/signup', testSignUp);
router.post('/test/login', testLogin);
router.get('/me', authenticate, me);
router.delete('/me', authenticate, deleteMyAccount);
router.get('/user/me', authenticateCustomer, customerMe);
router.delete('/user/me', authenticateCustomer, deleteCustomerAccount);
router.get('/customers', authenticate, allowRoles('master', 'admin'), listCustomers);
router.get('/customers/:id', authenticate, allowRoles('master', 'admin'), getCustomer);
router.patch('/customers/:id', authenticate, allowRoles('master', 'admin'), updateCustomer);
router.delete('/customers/:id', authenticate, allowRoles('master', 'admin'), deleteManagedCustomer);
router.get('/users', authenticate, allowRoles('master', 'admin'), listUsers);
router.get('/users/:id', authenticate, allowRoles('master', 'admin'), getUser);
router.patch('/users/:id', authenticate, allowRoles('master', 'admin'), updateUser);
router.delete('/users/:id', authenticate, allowRoles('master', 'admin'), deleteUser);
router.patch('/users/:id/role', authenticate, allowRoles('master'), updateUserRole);
export default router;
