import { Router } from 'express';
import { kakaoLogin, kakaoSignUp, me, testLogin, testSignUp, updateUserRole } from '../controllers/authController.js';
import { allowRoles, authenticate } from '../middleware/auth.js';
const router = Router();
router.post('/kakao/signup', kakaoSignUp);
router.post('/kakao/login', kakaoLogin);
router.post('/test/signup', testSignUp);
router.post('/test/login', testLogin);
router.get('/me', authenticate, me);
router.patch('/users/:id/role', authenticate, allowRoles('master'), updateUserRole);
export default router;
